
name: $(date:yyyyMMdd)$(rev:.r)
jobs:
- job: create_artifacts
  displayName: Terraform Artifact Creation
  pool:
    vmImage: vs2017-win2016
  steps:
  - checkout: self
# Copy Terraform Files into Artifacts Folder
  - task: CopyFiles@2
    displayName: Copy Terraform Files to Artifacts
    inputs:
      SourceFolder: .
      TargetFolder: $(build.artifactstagingdirectory)
  
    # Create Artifact for Release Consumption 
  - task: PublishBuildArtifacts@1
    displayName: Publish Combined Artifact
    condition: succeededOrFailed()
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'
