
trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: testing_tf
  displayName: "testingtf"
  steps:
  - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
    displayName: 'Use Terraform latest'
  - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
    displayName: 'terraform init'
    inputs:
      command: init
      backendType: azurerm
      backendServiceArm: 'spn-devops-1'
      ensureBackend: true
      backendAzureRmResourceGroupName: 'rg-terraform-service '
      backendAzureRmResourceGroupLocation: uksouth
      backendAzureRmStorageAccountName: stbuildtfstate
      backendAzureRmContainerName: 'resource-tag'
      backendAzureRmKey: github.tfstate
