
trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: testing_tf
  displayName: "testingtf"
  steps:
  - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
    displayName: 'Use Terraform latest'